# https://www.iso.org/obp/ui/#search

COUNTRIES = {
    "AF": {
        "code": "AF",
        "name": "Afghanistan",
        "continent": "AS",
        "emoji": "🇦🇫",
        "continent_name": "Asia",
    },
    "AL": {
        "code": "AL",
        "name": "Albania",
        "continent": "EU",
        "emoji": "🇦🇱",
        "continent_name": "Europe",
    },
    "DZ": {
        "code": "DZ",
        "name": "Algeria",
        "continent": "AF",
        "emoji": "🇩🇿",
        "continent_name": "Africa",
    },
    "AS": {
        "code": "AS",
        "name": "American Samoa",
        "continent": "OC",
        "emoji": "🇦🇸",
        "continent_name": "Oceania",
    },
    "AD": {
        "code": "AD",
        "name": "Andorra",
        "continent": "EU",
        "emoji": "🇦🇩",
        "continent_name": "Europe",
    },
    "AO": {
        "code": "AO",
        "name": "Angola",
        "continent": "AF",
        "emoji": "🇦🇴",
        "continent_name": "Africa",
    },
    "AI": {
        "code": "AI",
        "name": "Anguilla",
        "continent": "NA",
        "emoji": "🇦🇮",
        "continent_name": "North America",
    },
    "AQ": {
        "code": "AQ",
        "name": "Antarctica",
        "continent": "AN",
        "emoji": "🇦🇶",
        "continent_name": "Antarctica",
    },
    "AG": {
        "code": "AG",
        "name": "Antigua and Barbuda",
        "continent": "NA",
        "emoji": "🇦🇬",
        "continent_name": "North America",
    },
    "AR": {
        "code": "AR",
        "name": "Argentina",
        "continent": "SA",
        "emoji": "🇦🇷",
        "continent_name": "South America",
    },
    "AM": {
        "code": "AM",
        "name": "Armenia",
        "continent": "AS",
        "emoji": "🇦🇲",
        "continent_name": "Asia",
    },
    "AW": {
        "code": "AW",
        "name": "Aruba",
        "continent": "NA",
        "emoji": "🇦🇼",
        "continent_name": "North America",
    },
    "AU": {
        "code": "AU",
        "name": "Australia",
        "continent": "OC",
        "emoji": "🇦🇺",
        "continent_name": "Oceania",
    },
    "AT": {
        "code": "AT",
        "name": "Austria",
        "continent": "EU",
        "emoji": "🇦🇹",
        "continent_name": "Europe",
    },
    "AZ": {
        "code": "AZ",
        "name": "Azerbaijan",
        "continent": "AS",
        "emoji": "🇦🇿",
        "continent_name": "Asia",
    },
    "BS": {
        "code": "BS",
        "name": "Bahamas",
        "continent": "NA",
        "emoji": "🇧🇸",
        "continent_name": "North America",
    },
    "BH": {
        "code": "BH",
        "name": "Bahrain",
        "continent": "AS",
        "emoji": "🇧🇭",
        "continent_name": "Asia",
    },
    "BD": {
        "code": "BD",
        "name": "Bangladesh",
        "continent": "AS",
        "emoji": "🇧🇩",
        "continent_name": "Asia",
    },
    "BB": {
        "code": "BB",
        "name": "Barbados",
        "continent": "NA",
        "emoji": "🇧🇧",
        "continent_name": "North America",
    },
    "BY": {
        "code": "BY",
        "name": "Belarus",
        "continent": "EU",
        "emoji": "🇧🇾",
        "continent_name": "Europe",
    },
    "BE": {
        "code": "BE",
        "name": "Belgium",
        "continent": "EU",
        "emoji": "🇧🇪",
        "continent_name": "Europe",
    },
    "BZ": {
        "code": "BZ",
        "name": "Belize",
        "continent": "NA",
        "emoji": "🇧🇿",
        "continent_name": "North America",
    },
    "BJ": {
        "code": "BJ",
        "name": "Benin",
        "continent": "AF",
        "emoji": "🇧🇯",
        "continent_name": "Africa",
    },
    "BM": {
        "code": "BM",
        "name": "Bermuda",
        "continent": "NA",
        "emoji": "🇧🇲",
        "continent_name": "North America",
    },
    "BT": {
        "code": "BT",
        "name": "Bhutan",
        "continent": "AS",
        "emoji": "🇧🇹",
        "continent_name": "Asia",
    },
    "BO": {
        "code": "BO",
        "name": "Bolivia, Plurinational State of",
        "continent": "SA",
        "emoji": "🇧🇴",
        "continent_name": "South America",
    },
    "BQ": {
        "code": "BQ",
        "name": "Bonaire, Sint Eustatius and Saba",
        "continent": "NA",
        "emoji": "🇧🇶",
        "continent_name": "North America",
    },
    "BA": {
        "code": "BA",
        "name": "Bosnia and Herzegovina",
        "continent": "EU",
        "emoji": "🇧🇦",
        "continent_name": "Europe",
    },
    "BW": {
        "code": "BW",
        "name": "Botswana",
        "continent": "AF",
        "emoji": "🇧🇼",
        "continent_name": "Africa",
    },
    "BV": {
        "code": "BV",
        "name": "Bouvet Island",
        "continent": "AN",
        "emoji": "🇧🇻",
        "continent_name": "Antarctica",
    },
    "BR": {
        "code": "BR",
        "name": "Brazil",
        "continent": "SA",
        "emoji": "🇧🇷",
        "continent_name": "South America",
    },
    "IO": {
        "code": "IO",
        "name": "British Indian Ocean Territory",
        "continent": "AS",
        "emoji": "🇮🇴",
        "continent_name": "Asia",
    },
    "BN": {
        "code": "BN",
        "name": "Brunei Darussalam",
        "continent": "AS",
        "emoji": "🇧🇳",
        "continent_name": "Asia",
    },
    "BG": {
        "code": "BG",
        "name": "Bulgaria",
        "continent": "EU",
        "emoji": "🇧🇬",
        "continent_name": "Europe",
    },
    "BF": {
        "code": "BF",
        "name": "Burkina Faso",
        "continent": "AF",
        "emoji": "🇧🇫",
        "continent_name": "Africa",
    },
    "BI": {
        "code": "BI",
        "name": "Burundi",
        "continent": "AF",
        "emoji": "🇧🇮",
        "continent_name": "Africa",
    },
    "CV": {
        "code": "CV",
        "name": "Cabo Verde",
        "continent": "AF",
        "emoji": "🇨🇻",
        "continent_name": "Africa",
    },
    "KH": {
        "code": "KH",
        "name": "Cambodia",
        "continent": "AS",
        "emoji": "🇰🇭",
        "continent_name": "Asia",
    },
    "CM": {
        "code": "CM",
        "name": "Cameroon",
        "continent": "AF",
        "emoji": "🇨🇲",
        "continent_name": "Africa",
    },
    "CA": {
        "code": "CA",
        "name": "Canada",
        "continent": "NA",
        "emoji": "🇨🇦",
        "continent_name": "North America",
    },
    "KY": {
        "code": "KY",
        "name": "Cayman Islands",
        "continent": "NA",
        "emoji": "🇰🇾",
        "continent_name": "North America",
    },
    "CF": {
        "code": "CF",
        "name": "Central African Republic",
        "continent": "AF",
        "emoji": "🇨🇫",
        "continent_name": "Africa",
    },
    "TD": {
        "code": "TD",
        "name": "Chad",
        "continent": "AF",
        "emoji": "🇹🇩",
        "continent_name": "Africa",
    },
    "CL": {
        "code": "CL",
        "name": "Chile",
        "continent": "SA",
        "emoji": "🇨🇱",
        "continent_name": "South America",
    },
    "CN": {
        "code": "CN",
        "name": "China",
        "continent": "AS",
        "emoji": "🇨🇳",
        "continent_name": "Asia",
    },
    "CX": {
        "code": "CX",
        "name": "Christmas Island",
        "continent": "OC",
        "emoji": "🇨🇽",
        "continent_name": "Oceania",
    },
    "CC": {
        "code": "CC",
        "name": "Cocos (Keeling) Islands",
        "continent": "AS",
        "emoji": "🇨🇨",
        "continent_name": "Asia",
    },
    "CO": {
        "code": "CO",
        "name": "Colombia",
        "continent": "SA",
        "emoji": "🇨🇴",
        "continent_name": "South America",
    },
    "KM": {
        "code": "KM",
        "name": "Comoros",
        "continent": "AF",
        "emoji": "🇰🇲",
        "continent_name": "Africa",
    },
    "CG": {
        "code": "CG",
        "name": "Congo",
        "continent": "AF",
        "emoji": "🇨🇬",
        "continent_name": "Africa",
    },
    "CD": {
        "code": "CD",
        "name": "Congo, The Democratic Republic of the",
        "continent": "AF",
        "emoji": "🇨🇩",
        "continent_name": "Africa",
    },
    "CK": {
        "code": "CK",
        "name": "Cook Islands",
        "continent": "OC",
        "emoji": "🇨🇰",
        "continent_name": "Oceania",
    },
    "CR": {
        "code": "CR",
        "name": "Costa Rica",
        "continent": "NA",
        "emoji": "🇨🇷",
        "continent_name": "North America",
    },
    "HR": {
        "code": "HR",
        "name": "Croatia",
        "continent": "EU",
        "emoji": "🇭🇷",
        "continent_name": "Europe",
    },
    "CU": {
        "code": "CU",
        "name": "Cuba",
        "continent": "NA",
        "emoji": "🇨🇺",
        "continent_name": "North America",
    },
    "CW": {
        "code": "CW",
        "name": "Curaçao",
        "continent": "NA",
        "emoji": "🇨🇼",
        "continent_name": "North America",
    },
    "CY": {
        "code": "CY",
        "name": "Cyprus",
        "continent": "EU",
        "emoji": "🇨🇾",
        "continent_name": "Europe",
    },
    "CZ": {
        "code": "CZ",
        "name": "Czechia",
        "continent": "EU",
        "emoji": "🇨🇿",
        "continent_name": "Europe",
    },
    "CI": {
        "code": "CI",
        "name": "Côte d'Ivoire",
        "continent": "AF",
        "emoji": "🇨🇮",
        "continent_name": "Africa",
    },
    "DK": {
        "code": "DK",
        "name": "Denmark",
        "continent": "EU",
        "emoji": "🇩🇰",
        "continent_name": "Europe",
    },
    "DJ": {
        "code": "DJ",
        "name": "Djibouti",
        "continent": "AF",
        "emoji": "🇩🇯",
        "continent_name": "Africa",
    },
    "DM": {
        "code": "DM",
        "name": "Dominica",
        "continent": "NA",
        "emoji": "🇩🇲",
        "continent_name": "North America",
    },
    "DO": {
        "code": "DO",
        "name": "Dominican Republic",
        "continent": "NA",
        "emoji": "🇩🇴",
        "continent_name": "North America",
    },
    "EC": {
        "code": "EC",
        "name": "Ecuador",
        "continent": "SA",
        "emoji": "🇪🇨",
        "continent_name": "South America",
    },
    "EG": {
        "code": "EG",
        "name": "Egypt",
        "continent": "AF",
        "emoji": "🇪🇬",
        "continent_name": "Africa",
    },
    "SV": {
        "code": "SV",
        "name": "El Salvador",
        "continent": "NA",
        "emoji": "🇸🇻",
        "continent_name": "North America",
    },
    "GQ": {
        "code": "GQ",
        "name": "Equatorial Guinea",
        "continent": "AF",
        "emoji": "🇬🇶",
        "continent_name": "Africa",
    },
    "ER": {
        "code": "ER",
        "name": "Eritrea",
        "continent": "AF",
        "emoji": "🇪🇷",
        "continent_name": "Africa",
    },
    "EE": {
        "code": "EE",
        "name": "Estonia",
        "continent": "EU",
        "emoji": "🇪🇪",
        "continent_name": "Europe",
    },
    "SZ": {
        "code": "SZ",
        "name": "Eswatini",
        "continent": "AF",
        "emoji": "🇸🇿",
        "continent_name": "Africa",
    },
    "ET": {
        "code": "ET",
        "name": "Ethiopia",
        "continent": "AF",
        "emoji": "🇪🇹",
        "continent_name": "Africa",
    },
    "FK": {
        "code": "FK",
        "name": "Falkland Islands (Malvinas)",
        "continent": "SA",
        "emoji": "🇫🇰",
        "continent_name": "South America",
    },
    "FO": {
        "code": "FO",
        "name": "Faroe Islands",
        "continent": "EU",
        "emoji": "🇫🇴",
        "continent_name": "Europe",
    },
    "FJ": {
        "code": "FJ",
        "name": "Fiji",
        "continent": "OC",
        "emoji": "🇫🇯",
        "continent_name": "Oceania",
    },
    "FI": {
        "code": "FI",
        "name": "Finland",
        "continent": "EU",
        "emoji": "🇫🇮",
        "continent_name": "Europe",
    },
    "FR": {
        "code": "FR",
        "name": "France",
        "continent": "EU",
        "emoji": "🇫🇷",
        "continent_name": "Europe",
    },
    "GF": {
        "code": "GF",
        "name": "French Guiana",
        "continent": "SA",
        "emoji": "🇬🇫",
        "continent_name": "South America",
    },
    "PF": {
        "code": "PF",
        "name": "French Polynesia",
        "continent": "OC",
        "emoji": "🇵🇫",
        "continent_name": "Oceania",
    },
    "TF": {
        "code": "TF",
        "name": "French Southern Territories",
        "continent": "AN",
        "emoji": "🇹🇫",
        "continent_name": "Antarctica",
    },
    "GA": {
        "code": "GA",
        "name": "Gabon",
        "continent": "AF",
        "emoji": "🇬🇦",
        "continent_name": "Africa",
    },
    "GM": {
        "code": "GM",
        "name": "Gambia",
        "continent": "AF",
        "emoji": "🇬🇲",
        "continent_name": "Africa",
    },
    "GE": {
        "code": "GE",
        "name": "Georgia",
        "continent": "AS",
        "emoji": "🇬🇪",
        "continent_name": "Asia",
    },
    "DE": {
        "code": "DE",
        "name": "Germany",
        "continent": "EU",
        "emoji": "🇩🇪",
        "continent_name": "Europe",
    },
    "GH": {
        "code": "GH",
        "name": "Ghana",
        "continent": "AF",
        "emoji": "🇬🇭",
        "continent_name": "Africa",
    },
    "GI": {
        "code": "GI",
        "name": "Gibraltar",
        "continent": "EU",
        "emoji": "🇬🇮",
        "continent_name": "Europe",
    },
    "GR": {
        "code": "GR",
        "name": "Greece",
        "continent": "EU",
        "emoji": "🇬🇷",
        "continent_name": "Europe",
    },
    "GL": {
        "code": "GL",
        "name": "Greenland",
        "continent": "NA",
        "emoji": "🇬🇱",
        "continent_name": "North America",
    },
    "GD": {
        "code": "GD",
        "name": "Grenada",
        "continent": "NA",
        "emoji": "🇬🇩",
        "continent_name": "North America",
    },
    "GP": {
        "code": "GP",
        "name": "Guadeloupe",
        "continent": "NA",
        "emoji": "🇬🇵",
        "continent_name": "North America",
    },
    "GU": {
        "code": "GU",
        "name": "Guam",
        "continent": "OC",
        "emoji": "🇬🇺",
        "continent_name": "Oceania",
    },
    "GT": {
        "code": "GT",
        "name": "Guatemala",
        "continent": "NA",
        "emoji": "🇬🇹",
        "continent_name": "North America",
    },
    "GG": {
        "code": "GG",
        "name": "Guernsey",
        "continent": "EU",
        "emoji": "🇬🇬",
        "continent_name": "Europe",
    },
    "GN": {
        "code": "GN",
        "name": "Guinea",
        "continent": "AF",
        "emoji": "🇬🇳",
        "continent_name": "Africa",
    },
    "GW": {
        "code": "GW",
        "name": "Guinea-Bissau",
        "continent": "AF",
        "emoji": "🇬🇼",
        "continent_name": "Africa",
    },
    "GY": {
        "code": "GY",
        "name": "Guyana",
        "continent": "SA",
        "emoji": "🇬🇾",
        "continent_name": "South America",
    },
    "HT": {
        "code": "HT",
        "name": "Haiti",
        "continent": "NA",
        "emoji": "🇭🇹",
        "continent_name": "North America",
    },
    "HM": {
        "code": "HM",
        "name": "Heard Island and McDonald Islands",
        "continent": "AN",
        "emoji": "🇭🇲",
        "continent_name": "Antarctica",
    },
    "VA": {
        "code": "VA",
        "name": "Holy See (Vatican City State)",
        "continent": "EU",
        "emoji": "🇻🇦",
        "continent_name": "Europe",
    },
    "HN": {
        "code": "HN",
        "name": "Honduras",
        "continent": "NA",
        "emoji": "🇭🇳",
        "continent_name": "North America",
    },
    "HK": {
        "code": "HK",
        "name": "Hong Kong",
        "continent": "AS",
        "emoji": "🇭🇰",
        "continent_name": "Asia",
    },
    "HU": {
        "code": "HU",
        "name": "Hungary",
        "continent": "EU",
        "emoji": "🇭🇺",
        "continent_name": "Europe",
    },
    "IS": {
        "code": "IS",
        "name": "Iceland",
        "continent": "EU",
        "emoji": "🇮🇸",
        "continent_name": "Europe",
    },
    "IN": {
        "code": "IN",
        "name": "India",
        "continent": "AS",
        "emoji": "🇮🇳",
        "continent_name": "Asia",
    },
    "ID": {
        "code": "ID",
        "name": "Indonesia",
        "continent": "AS",
        "emoji": "🇮🇩",
        "continent_name": "Asia",
    },
    "IR": {
        "code": "IR",
        "name": "Iran, Islamic Republic of",
        "continent": "AS",
        "emoji": "🇮🇷",
        "continent_name": "Asia",
    },
    "IQ": {
        "code": "IQ",
        "name": "Iraq",
        "continent": "AS",
        "emoji": "🇮🇶",
        "continent_name": "Asia",
    },
    "IE": {
        "code": "IE",
        "name": "Ireland",
        "continent": "EU",
        "emoji": "🇮🇪",
        "continent_name": "Europe",
    },
    "IM": {
        "code": "IM",
        "name": "Isle of Man",
        "continent": "EU",
        "emoji": "🇮🇲",
        "continent_name": "Europe",
    },
    "IL": {
        "code": "IL",
        "name": "Israel",
        "continent": "AS",
        "emoji": "🇮🇱",
        "continent_name": "Asia",
    },
    "IT": {
        "code": "IT",
        "name": "Italy",
        "continent": "EU",
        "emoji": "🇮🇹",
        "continent_name": "Europe",
    },
    "JM": {
        "code": "JM",
        "name": "Jamaica",
        "continent": "NA",
        "emoji": "🇯🇲",
        "continent_name": "North America",
    },
    "JP": {
        "code": "JP",
        "name": "Japan",
        "continent": "AS",
        "emoji": "🇯🇵",
        "continent_name": "Asia",
    },
    "JE": {
        "code": "JE",
        "name": "Jersey",
        "continent": "EU",
        "emoji": "🇯🇪",
        "continent_name": "Europe",
    },
    "JO": {
        "code": "JO",
        "name": "Jordan",
        "continent": "AS",
        "emoji": "🇯🇴",
        "continent_name": "Asia",
    },
    "KZ": {
        "code": "KZ",
        "name": "Kazakhstan",
        "continent": "AS",
        "emoji": "🇰🇿",
        "continent_name": "Asia",
    },
    "KE": {
        "code": "KE",
        "name": "Kenya",
        "continent": "AF",
        "emoji": "🇰🇪",
        "continent_name": "Africa",
    },
    "KI": {
        "code": "KI",
        "name": "Kiribati",
        "continent": "OC",
        "emoji": "🇰🇮",
        "continent_name": "Oceania",
    },
    "KP": {
        "code": "KP",
        "name": "Korea, Democratic People's Republic of",
        "continent": "AS",
        "emoji": "🇰🇵",
        "continent_name": "Asia",
    },
    "KR": {
        "code": "KR",
        "name": "Korea, Republic of",
        "continent": "AS",
        "emoji": "🇰🇷",
        "continent_name": "Asia",
    },
    "KW": {
        "code": "KW",
        "name": "Kuwait",
        "continent": "AS",
        "emoji": "🇰🇼",
        "continent_name": "Asia",
    },
    "KG": {
        "code": "KG",
        "name": "Kyrgyzstan",
        "continent": "AS",
        "emoji": "🇰🇬",
        "continent_name": "Asia",
    },
    "LA": {
        "code": "LA",
        "name": "Lao People's Democratic Republic",
        "continent": "AS",
        "emoji": "🇱🇦",
        "continent_name": "Asia",
    },
    "LV": {
        "code": "LV",
        "name": "Latvia",
        "continent": "EU",
        "emoji": "🇱🇻",
        "continent_name": "Europe",
    },
    "LB": {
        "code": "LB",
        "name": "Lebanon",
        "continent": "AS",
        "emoji": "🇱🇧",
        "continent_name": "Asia",
    },
    "LS": {
        "code": "LS",
        "name": "Lesotho",
        "continent": "AF",
        "emoji": "🇱🇸",
        "continent_name": "Africa",
    },
    "LR": {
        "code": "LR",
        "name": "Liberia",
        "continent": "AF",
        "emoji": "🇱🇷",
        "continent_name": "Africa",
    },
    "LY": {
        "code": "LY",
        "name": "Libya",
        "continent": "AF",
        "emoji": "🇱🇾",
        "continent_name": "Africa",
    },
    "LI": {
        "code": "LI",
        "name": "Liechtenstein",
        "continent": "EU",
        "emoji": "🇱🇮",
        "continent_name": "Europe",
    },
    "LT": {
        "code": "LT",
        "name": "Lithuania",
        "continent": "EU",
        "emoji": "🇱🇹",
        "continent_name": "Europe",
    },
    "LU": {
        "code": "LU",
        "name": "Luxembourg",
        "continent": "EU",
        "emoji": "🇱🇺",
        "continent_name": "Europe",
    },
    "MO": {
        "code": "MO",
        "name": "Macao",
        "continent": "AS",
        "emoji": "🇲🇴",
        "continent_name": "Asia",
    },
    "MG": {
        "code": "MG",
        "name": "Madagascar",
        "continent": "AF",
        "emoji": "🇲🇬",
        "continent_name": "Africa",
    },
    "MW": {
        "code": "MW",
        "name": "Malawi",
        "continent": "AF",
        "emoji": "🇲🇼",
        "continent_name": "Africa",
    },
    "MY": {
        "code": "MY",
        "name": "Malaysia",
        "continent": "AS",
        "emoji": "🇲🇾",
        "continent_name": "Asia",
    },
    "MV": {
        "code": "MV",
        "name": "Maldives",
        "continent": "AS",
        "emoji": "🇲🇻",
        "continent_name": "Asia",
    },
    "ML": {
        "code": "ML",
        "name": "Mali",
        "continent": "AF",
        "emoji": "🇲🇱",
        "continent_name": "Africa",
    },
    "MT": {
        "code": "MT",
        "name": "Malta",
        "continent": "EU",
        "emoji": "🇲🇹",
        "continent_name": "Europe",
    },
    "MH": {
        "code": "MH",
        "name": "Marshall Islands",
        "continent": "OC",
        "emoji": "🇲🇭",
        "continent_name": "Oceania",
    },
    "MQ": {
        "code": "MQ",
        "name": "Martinique",
        "continent": "NA",
        "emoji": "🇲🇶",
        "continent_name": "North America",
    },
    "MR": {
        "code": "MR",
        "name": "Mauritania",
        "continent": "AF",
        "emoji": "🇲🇷",
        "continent_name": "Africa",
    },
    "MU": {
        "code": "MU",
        "name": "Mauritius",
        "continent": "AF",
        "emoji": "🇲🇺",
        "continent_name": "Africa",
    },
    "YT": {
        "code": "YT",
        "name": "Mayotte",
        "continent": "AF",
        "emoji": "🇾🇹",
        "continent_name": "Africa",
    },
    "MX": {
        "code": "MX",
        "name": "Mexico",
        "continent": "NA",
        "emoji": "🇲🇽",
        "continent_name": "North America",
    },
    "FM": {
        "code": "FM",
        "name": "Micronesia, Federated States of",
        "continent": "OC",
        "emoji": "🇫🇲",
        "continent_name": "Oceania",
    },
    "MD": {
        "code": "MD",
        "name": "Moldova, Republic of",
        "continent": "EU",
        "emoji": "🇲🇩",
        "continent_name": "Europe",
    },
    "MC": {
        "code": "MC",
        "name": "Monaco",
        "continent": "EU",
        "emoji": "🇲🇨",
        "continent_name": "Europe",
    },
    "MN": {
        "code": "MN",
        "name": "Mongolia",
        "continent": "AS",
        "emoji": "🇲🇳",
        "continent_name": "Asia",
    },
    "ME": {
        "code": "ME",
        "name": "Montenegro",
        "continent": "EU",
        "emoji": "🇲🇪",
        "continent_name": "Europe",
    },
    "MS": {
        "code": "MS",
        "name": "Montserrat",
        "continent": "NA",
        "emoji": "🇲🇸",
        "continent_name": "North America",
    },
    "MA": {
        "code": "MA",
        "name": "Morocco",
        "continent": "AF",
        "emoji": "🇲🇦",
        "continent_name": "Africa",
    },
    "MZ": {
        "code": "MZ",
        "name": "Mozambique",
        "continent": "AF",
        "emoji": "🇲🇿",
        "continent_name": "Africa",
    },
    "MM": {
        "code": "MM",
        "name": "Myanmar",
        "continent": "AS",
        "emoji": "🇲🇲",
        "continent_name": "Asia",
    },
    "NA": {
        "code": "NA",
        "name": "Namibia",
        "continent": "AF",
        "emoji": "🇳🇦",
        "continent_name": "Africa",
    },
    "NR": {
        "code": "NR",
        "name": "Nauru",
        "continent": "OC",
        "emoji": "🇳🇷",
        "continent_name": "Oceania",
    },
    "NP": {
        "code": "NP",
        "name": "Nepal",
        "continent": "AS",
        "emoji": "🇳🇵",
        "continent_name": "Asia",
    },
    "NL": {
        "code": "NL",
        "name": "Netherlands",
        "continent": "EU",
        "emoji": "🇳🇱",
        "continent_name": "Europe",
    },
    "NC": {
        "code": "NC",
        "name": "New Caledonia",
        "continent": "OC",
        "emoji": "🇳🇨",
        "continent_name": "Oceania",
    },
    "NZ": {
        "code": "NZ",
        "name": "New Zealand",
        "continent": "OC",
        "emoji": "🇳🇿",
        "continent_name": "Oceania",
    },
    "NI": {
        "code": "NI",
        "name": "Nicaragua",
        "continent": "NA",
        "emoji": "🇳🇮",
        "continent_name": "North America",
    },
    "NE": {
        "code": "NE",
        "name": "Niger",
        "continent": "AF",
        "emoji": "🇳🇪",
        "continent_name": "Africa",
    },
    "NG": {
        "code": "NG",
        "name": "Nigeria",
        "continent": "AF",
        "emoji": "🇳🇬",
        "continent_name": "Africa",
    },
    "NU": {
        "code": "NU",
        "name": "Niue",
        "continent": "OC",
        "emoji": "🇳🇺",
        "continent_name": "Oceania",
    },
    "NF": {
        "code": "NF",
        "name": "Norfolk Island",
        "continent": "OC",
        "emoji": "🇳🇫",
        "continent_name": "Oceania",
    },
    "MK": {
        "code": "MK",
        "name": "North Macedonia",
        "continent": "EU",
        "emoji": "🇲🇰",
        "continent_name": "Europe",
    },
    "MP": {
        "code": "MP",
        "name": "Northern Mariana Islands",
        "continent": "OC",
        "emoji": "🇲🇵",
        "continent_name": "Oceania",
    },
    "NO": {
        "code": "NO",
        "name": "Norway",
        "continent": "EU",
        "emoji": "🇳🇴",
        "continent_name": "Europe",
    },
    "OM": {
        "code": "OM",
        "name": "Oman",
        "continent": "AS",
        "emoji": "🇴🇲",
        "continent_name": "Asia",
    },
    "PK": {
        "code": "PK",
        "name": "Pakistan",
        "continent": "AS",
        "emoji": "🇵🇰",
        "continent_name": "Asia",
    },
    "PW": {
        "code": "PW",
        "name": "Palau",
        "continent": "OC",
        "emoji": "🇵🇼",
        "continent_name": "Oceania",
    },
    "PS": {
        "code": "PS",
        "name": "Palestine, State of",
        "continent": "AS",
        "emoji": "🇵🇸",
        "continent_name": "Asia",
    },
    "PA": {
        "code": "PA",
        "name": "Panama",
        "continent": "NA",
        "emoji": "🇵🇦",
        "continent_name": "North America",
    },
    "PG": {
        "code": "PG",
        "name": "Papua New Guinea",
        "continent": "OC",
        "emoji": "🇵🇬",
        "continent_name": "Oceania",
    },
    "PY": {
        "code": "PY",
        "name": "Paraguay",
        "continent": "SA",
        "emoji": "🇵🇾",
        "continent_name": "South America",
    },
    "PE": {
        "code": "PE",
        "name": "Peru",
        "continent": "SA",
        "emoji": "🇵🇪",
        "continent_name": "South America",
    },
    "PH": {
        "code": "PH",
        "name": "Philippines",
        "continent": "AS",
        "emoji": "🇵🇭",
        "continent_name": "Asia",
    },
    "PN": {
        "code": "PN",
        "name": "Pitcairn",
        "continent": "OC",
        "emoji": "🇵🇳",
        "continent_name": "Oceania",
    },
    "PL": {
        "code": "PL",
        "name": "Poland",
        "continent": "EU",
        "emoji": "🇵🇱",
        "continent_name": "Europe",
    },
    "PT": {
        "code": "PT",
        "name": "Portugal",
        "continent": "EU",
        "emoji": "🇵🇹",
        "continent_name": "Europe",
    },
    "PR": {
        "code": "PR",
        "name": "Puerto Rico",
        "continent": "NA",
        "emoji": "🇵🇷",
        "continent_name": "North America",
    },
    "QA": {
        "code": "QA",
        "name": "Qatar",
        "continent": "AS",
        "emoji": "🇶🇦",
        "continent_name": "Asia",
    },
    "RO": {
        "code": "RO",
        "name": "Romania",
        "continent": "EU",
        "emoji": "🇷🇴",
        "continent_name": "Europe",
    },
    "RU": {
        "code": "RU",
        "name": "Russian Federation",
        "continent": "EU",
        "emoji": "🇷🇺",
        "continent_name": "Europe",
    },
    "RW": {
        "code": "RW",
        "name": "Rwanda",
        "continent": "AF",
        "emoji": "🇷🇼",
        "continent_name": "Africa",
    },
    "RE": {
        "code": "RE",
        "name": "Réunion",
        "continent": "AF",
        "emoji": "🇷🇪",
        "continent_name": "Africa",
    },
    "BL": {
        "code": "BL",
        "name": "Saint Barthélemy",
        "continent": "NA",
        "emoji": "🇧🇱",
        "continent_name": "North America",
    },
    "SH": {
        "code": "SH",
        "name": "Saint Helena, Ascension and Tristan da Cunha",
        "continent": "AF",
        "emoji": "🇸🇭",
        "continent_name": "Africa",
    },
    "KN": {
        "code": "KN",
        "name": "Saint Kitts and Nevis",
        "continent": "NA",
        "emoji": "🇰🇳",
        "continent_name": "North America",
    },
    "LC": {
        "code": "LC",
        "name": "Saint Lucia",
        "continent": "NA",
        "emoji": "🇱🇨",
        "continent_name": "North America",
    },
    "MF": {
        "code": "MF",
        "name": "Saint Martin (French part)",
        "continent": "NA",
        "emoji": "🇲🇫",
        "continent_name": "North America",
    },
    "PM": {
        "code": "PM",
        "name": "Saint Pierre and Miquelon",
        "continent": "NA",
        "emoji": "🇵🇲",
        "continent_name": "North America",
    },
    "VC": {
        "code": "VC",
        "name": "Saint Vincent and the Grenadines",
        "continent": "NA",
        "emoji": "🇻🇨",
        "continent_name": "North America",
    },
    "WS": {
        "code": "WS",
        "name": "Samoa",
        "continent": "OC",
        "emoji": "🇼🇸",
        "continent_name": "Oceania",
    },
    "SM": {
        "code": "SM",
        "name": "San Marino",
        "continent": "EU",
        "emoji": "🇸🇲",
        "continent_name": "Europe",
    },
    "ST": {
        "code": "ST",
        "name": "Sao Tome and Principe",
        "continent": "AF",
        "emoji": "🇸🇹",
        "continent_name": "Africa",
    },
    "SA": {
        "code": "SA",
        "name": "Saudi Arabia",
        "continent": "AS",
        "emoji": "🇸🇦",
        "continent_name": "Asia",
    },
    "SN": {
        "code": "SN",
        "name": "Senegal",
        "continent": "AF",
        "emoji": "🇸🇳",
        "continent_name": "Africa",
    },
    "RS": {
        "code": "RS",
        "name": "Serbia",
        "continent": "EU",
        "emoji": "🇷🇸",
        "continent_name": "Europe",
    },
    "SC": {
        "code": "SC",
        "name": "Seychelles",
        "continent": "AF",
        "emoji": "🇸🇨",
        "continent_name": "Africa",
    },
    "SL": {
        "code": "SL",
        "name": "Sierra Leone",
        "continent": "AF",
        "emoji": "🇸🇱",
        "continent_name": "Africa",
    },
    "SG": {
        "code": "SG",
        "name": "Singapore",
        "continent": "AS",
        "emoji": "🇸🇬",
        "continent_name": "Asia",
    },
    "SX": {
        "code": "SX",
        "name": "Sint Maarten (Dutch part)",
        "continent": "NA",
        "emoji": "🇸🇽",
        "continent_name": "North America",
    },
    "SK": {
        "code": "SK",
        "name": "Slovakia",
        "continent": "EU",
        "emoji": "🇸🇰",
        "continent_name": "Europe",
    },
    "SI": {
        "code": "SI",
        "name": "Slovenia",
        "continent": "EU",
        "emoji": "🇸🇮",
        "continent_name": "Europe",
    },
    "SB": {
        "code": "SB",
        "name": "Solomon Islands",
        "continent": "OC",
        "emoji": "🇸🇧",
        "continent_name": "Oceania",
    },
    "SO": {
        "code": "SO",
        "name": "Somalia",
        "continent": "AF",
        "emoji": "🇸🇴",
        "continent_name": "Africa",
    },
    "ZA": {
        "code": "ZA",
        "name": "South Africa",
        "continent": "AF",
        "emoji": "🇿🇦",
        "continent_name": "Africa",
    },
    "GS": {
        "code": "GS",
        "name": "South Georgia and the South Sandwich Islands",
        "continent": "AN",
        "emoji": "🇬🇸",
        "continent_name": "Antarctica",
    },
    "SS": {
        "code": "SS",
        "name": "South Sudan",
        "continent": "AF",
        "emoji": "🇸🇸",
        "continent_name": "Africa",
    },
    "ES": {
        "code": "ES",
        "name": "Spain",
        "continent": "EU",
        "emoji": "🇪🇸",
        "continent_name": "Europe",
    },
    "LK": {
        "code": "LK",
        "name": "Sri Lanka",
        "continent": "AS",
        "emoji": "🇱🇰",
        "continent_name": "Asia",
    },
    "SD": {
        "code": "SD",
        "name": "Sudan",
        "continent": "AF",
        "emoji": "🇸🇩",
        "continent_name": "Africa",
    },
    "SR": {
        "code": "SR",
        "name": "Suriname",
        "continent": "SA",
        "emoji": "🇸🇷",
        "continent_name": "South America",
    },
    "SJ": {
        "code": "SJ",
        "name": "Svalbard and Jan Mayen",
        "continent": "EU",
        "emoji": "🇸🇯",
        "continent_name": "Europe",
    },
    "SE": {
        "code": "SE",
        "name": "Sweden",
        "continent": "EU",
        "emoji": "🇸🇪",
        "continent_name": "Europe",
    },
    "CH": {
        "code": "CH",
        "name": "Switzerland",
        "continent": "EU",
        "emoji": "🇨🇭",
        "continent_name": "Europe",
    },
    "SY": {
        "code": "SY",
        "name": "Syrian Arab Republic",
        "continent": "AS",
        "emoji": "🇸🇾",
        "continent_name": "Asia",
    },
    "TW": {
        "code": "TW",
        "name": "Taiwan, Province of China",
        "continent": "AS",
        "emoji": "🇹🇼",
        "continent_name": "Asia",
    },
    "TJ": {
        "code": "TJ",
        "name": "Tajikistan",
        "continent": "AS",
        "emoji": "🇹🇯",
        "continent_name": "Asia",
    },
    "TZ": {
        "code": "TZ",
        "name": "Tanzania, United Republic of",
        "continent": "AF",
        "emoji": "🇹🇿",
        "continent_name": "Africa",
    },
    "TH": {
        "code": "TH",
        "name": "Thailand",
        "continent": "AS",
        "emoji": "🇹🇭",
        "continent_name": "Asia",
    },
    "TL": {
        "code": "TL",
        "name": "Timor-Leste",
        "continent": "OC",
        "emoji": "🇹🇱",
        "continent_name": "Oceania",
    },
    "TG": {
        "code": "TG",
        "name": "Togo",
        "continent": "AF",
        "emoji": "🇹🇬",
        "continent_name": "Africa",
    },
    "TK": {
        "code": "TK",
        "name": "Tokelau",
        "continent": "OC",
        "emoji": "🇹🇰",
        "continent_name": "Oceania",
    },
    "TO": {
        "code": "TO",
        "name": "Tonga",
        "continent": "OC",
        "emoji": "🇹🇴",
        "continent_name": "Oceania",
    },
    "TT": {
        "code": "TT",
        "name": "Trinidad and Tobago",
        "continent": "NA",
        "emoji": "🇹🇹",
        "continent_name": "North America",
    },
    "TN": {
        "code": "TN",
        "name": "Tunisia",
        "continent": "AF",
        "emoji": "🇹🇳",
        "continent_name": "Africa",
    },
    "TM": {
        "code": "TM",
        "name": "Turkmenistan",
        "continent": "AS",
        "emoji": "🇹🇲",
        "continent_name": "Asia",
    },
    "TC": {
        "code": "TC",
        "name": "Turks and Caicos Islands",
        "continent": "NA",
        "emoji": "🇹🇨",
        "continent_name": "North America",
    },
    "TV": {
        "code": "TV",
        "name": "Tuvalu",
        "continent": "OC",
        "emoji": "🇹🇻",
        "continent_name": "Oceania",
    },
    "TR": {
        "code": "TR",
        "name": "Türkiye",
        "continent": "AS",
        "emoji": "🇹🇷",
        "continent_name": "Asia",
    },
    "UG": {
        "code": "UG",
        "name": "Uganda",
        "continent": "AF",
        "emoji": "🇺🇬",
        "continent_name": "Africa",
    },
    "UA": {
        "code": "UA",
        "name": "Ukraine",
        "continent": "EU",
        "emoji": "🇺🇦",
        "continent_name": "Europe",
    },
    "AE": {
        "code": "AE",
        "name": "United Arab Emirates",
        "continent": "AS",
        "emoji": "🇦🇪",
        "continent_name": "Asia",
    },
    "GB": {
        "code": "GB",
        "name": "UK",
        "continent": "EU",
        "emoji": "🇬🇧",
        "continent_name": "Europe",
    },
    "US": {
        "code": "US",
        "name": "United States",
        "continent": "NA",
        "emoji": "🇺🇸",
        "continent_name": "North America",
    },
    "UM": {
        "code": "UM",
        "name": "United States Minor Outlying Islands",
        "continent": "OC",
        "emoji": "🇺🇲",
        "continent_name": "Oceania",
    },
    "UY": {
        "code": "UY",
        "name": "Uruguay",
        "continent": "SA",
        "emoji": "🇺🇾",
        "continent_name": "South America",
    },
    "UZ": {
        "code": "UZ",
        "name": "Uzbekistan",
        "continent": "AS",
        "emoji": "🇺🇿",
        "continent_name": "Asia",
    },
    "VU": {
        "code": "VU",
        "name": "Vanuatu",
        "continent": "OC",
        "emoji": "🇻🇺",
        "continent_name": "Oceania",
    },
    "VE": {
        "code": "VE",
        "name": "Venezuela, Bolivarian Republic of",
        "continent": "SA",
        "emoji": "🇻🇪",
        "continent_name": "South America",
    },
    "VN": {
        "code": "VN",
        "name": "Viet Nam",
        "continent": "AS",
        "emoji": "🇻🇳",
        "continent_name": "Asia",
    },
    "VG": {
        "code": "VG",
        "name": "Virgin Islands, British",
        "continent": "NA",
        "emoji": "🇻🇬",
        "continent_name": "North America",
    },
    "VI": {
        "code": "VI",
        "name": "Virgin Islands, U.S.",
        "continent": "NA",
        "emoji": "🇻🇮",
        "continent_name": "North America",
    },
    "WF": {
        "code": "WF",
        "name": "Wallis and Futuna",
        "continent": "OC",
        "emoji": "🇼🇫",
        "continent_name": "Oceania",
    },
    "EH": {
        "code": "EH",
        "name": "Western Sahara",
        "continent": "AF",
        "emoji": "🇪🇭",
        "continent_name": "Africa",
    },
    "YE": {
        "code": "YE",
        "name": "Yemen",
        "continent": "AS",
        "emoji": "🇾🇪",
        "continent_name": "Asia",
    },
    "ZM": {
        "code": "ZM",
        "name": "Zambia",
        "continent": "AF",
        "emoji": "🇿🇲",
        "continent_name": "Africa",
    },
    "ZW": {
        "code": "ZW",
        "name": "Zimbabwe",
        "continent": "AF",
        "emoji": "🇿🇼",
        "continent_name": "Africa",
    },
    "AX": {
        "code": "AX",
        "name": "Åland Islands",
        "continent": "EU",
        "emoji": "🇦🇽",
        "continent_name": "Europe",
    },
}
